all:

test:
	chmod u+x *.sh
	./p01_a.sh
	./p02_b.sh
	./p03.sh > /dev/null
	./p04_a.sh
	./p04_b.sh
	./p05.sh
	./p06.sh
	./p07.sh
	./p08_a.sh
	./p08_b.sh
	./p08_c.sh
	./p08_d.sh
	./p08_e.sh
	./p09_a.sh
	# ./p10.sh
