all:

test:
	find . -name "*.sh" -exec chmod u+x {} \;
	./p01_a.sh
	./p01_b.sh
	./p01_c.sh
	./p02_a.sh
	./p02_b.sh
	./p02_c.sh
	./p03_a.sh
	./p03_b.sh
	./p04_a.sh
	./p04_c1.sh
	./p05_a.sh
	./p06.sh
	./p07.sh
