all:

test:
	./p02_a.sh
	./p02_b.sh
	./p03_a.sh
	./p03_b.sh
	./p03_c.sh
	./p04_a.sh
	./p04_b.sh
	./p05_a.sh
	./p05_b.sh
	./p05_c.sh
	./p05_d.sh
	./p06_a.sh
	./p06_c.sh
	./p06_d.sh
	./p06_e.sh
	./p06_f.sh
	./p06_g.sh
	./p06_h.sh
	./p07_a.sh
	./p07_b.sh
	./p08_a.sh
	./p08_b.sh
	./p09_a.sh
	