name: Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test-tp01:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: test tp01
      run: make tp01

  test-tp02:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: test tp02
      run: make tp02

  test-tp03:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: test tp03
      run: make tp03
